package com.easyapps.jetutilslib.utils


const val EMPTY = ""
const val ADS = "Ads"
const val PRO = "Pro"
const val LIBS = "Libs"
const val HOME = "Home"
const val QUIZ = "Quiz"
const val EXIT = "Exit"
const val RATE = "Rate"
const val BACK = "Back"
const val INIT = "Init"
const val THEME = "Theme"
const val SHARE = "Share"
const val TRASH = "Trash"
const val RESET = "Reset"
const val POLICY = "Policy"
const val DIALOG = "Dialog"
const val VIBRATE = "Vibrate"
const val PRIVACY = "Privacy"
const val ARCHIVE = "Archive"
const val RESULTS = "Results"
const val FEEDBACK = "Feedback"
const val DOWNLOAD = "Download"
const val SETTINGS = "Settings"
const val LANGUAGE = "Language"
const val EXPANDED = "Expanded"
const val SHUFFLE_ANSWERS = "Shuffle answers"
const val SHUFFLE_QUESTIONS= "Shuffle questions"

const val LAW = "Law"
const val ALL = "All"
const val RANDOM = "Random"
const val HISTORY = "History"